[package]
name = "demo_farm_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[example]]
name = "philosophers"

[[example]]
name = "philosophers_con"



[dependencies]
