[package]
name = "demo_practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"


[lib]
path  = "./src/thread/thread-executor.rs"  # This should match the name of your crate
